# Generated by Django 4.2.3 on 2023-08-10 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='static/images/profiles/default.webp', upload_to='static/images/profiles')),
                ('bio', models.CharField(max_length=1000, null=True)),
                ('github', models.URLField(max_length=64, null=True)),
                ('instagram', models.URLField(max_length=64, null=True)),
                ('twitter', models.URLField(max_length=64, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
