# Generated by Django 4.2.3 on 2023-08-13 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='user is too lazy to set name', max_length=128, null=True)),
                ('title', models.CharField(default='user is too lazy to set title', max_length=128, null=True)),
                ('profile_pic', models.ImageField(default='user/profiles/default', upload_to='user/profiles')),
                ('bio', models.CharField(default='user is too lazy to set bio', max_length=1000, null=True)),
                ('github', models.URLField(default='https://github.com/', max_length=64, null=True)),
                ('instagram', models.URLField(default='https://www.instagram.com/', max_length=64, null=True)),
                ('twitter', models.URLField(default='https://twitter.com/', max_length=64, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
