# Generated by Django 4.2.3 on 2023-08-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, default='enthusiast', max_length=128, null=True),
        ),
    ]
