# Generated by Django 4.2.3 on 2023-08-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='No Name', max_length=128, null=True),
        ),
    ]
