# Generated by Django 4.2.3 on 2023-08-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_bio_alter_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(default='https://github.com/', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.URLField(default='https://www.instagram.com/', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.URLField(default='https://twitter.com/', max_length=64, null=True),
        ),
    ]
