# Generated by Django 4.2.3 on 2023-08-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_github_alter_profile_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='user is too lazy to set bio', max_length=1000, null=True),
        ),
    ]
