# Generated by Django 4.2.3 on 2023-08-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='static/images/category/default.webp', upload_to='static/images/category/'),
        ),
    ]
