# Generated by Django 4.2.3 on 2023-08-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_excerpt_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='static/images/category/wall-e.webp', upload_to='static/images/category/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='static/images/default.webp', upload_to='static/images/thumbnails/'),
        ),
    ]
