# Generated by Django 4.2.3 on 2023-08-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_category_image_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='static/images/category/default.webp', upload_to='static/images/category/'),
        ),
    ]
