# Generated by Django 4.2.3 on 2023-08-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='media/images/default.webp', upload_to='media/images/thumbnails/'),
        ),
    ]
