# Generated by Django 4.2.3 on 2023-08-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='images/default.webp', upload_to='images/thumbnails/'),
        ),
    ]
