# Generated by Django 4.2.3 on 2023-08-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='blog/categories/default.webp', upload_to='blog/categories/'),
        ),
    ]
